name: Advent of Code 2021
type: dart
steps:
  - name: Day 1
    directory: day_01
    has_solution: true
  - name: Day 2 - part one
    directory: day_02
    has_solution: true
  - name: Day 2 - part two
    directory: day_02_2
    has_solution: true
  - name: Day 3 - part one
    directory: day_03
    has_solution: true
  - name: Day 3 - part two
    directory: day_03_2
    has_solution: true
  - name: Day 4 - part one
    directory: day_04
    has_solution: true
  - name: Day 4 - part two
    directory: day_04_2
    has_solution: true
  - name: Day 5 - part one
    directory: day_05
    has_solution: true
  - name: Day 5 - part two
    directory: day_05_2
    has_solution: true
  - name: Day 6 - part one
    directory: day_06
    has_solution: true
  - name: Day 6 - part two
    directory: day_06_2
    has_solution: true
  - name: Day 7 - part one
    directory: day_07
    has_solution: true
  - name: Day 7 - part two
    directory: day_07_2
    has_solution: true
  - name: Day 8 - part one
    directory: day_08
    has_solution: true
  - name: Day 8 - part two
    directory: day_08_2
    has_solution: true
  - name: Day 9 - part one
    directory: day_09
    has_solution: true
  - name: Day 9 - part two
    directory: day_09_2
    has_solution: true
  - name: Day 10 - part one
    directory: day_10
    has_solution: true
  - name: Day 10 - part two
    directory: day_10_2
    has_solution: true
  - name: Day 11 - part one
    directory: day_11
    has_solution: true
  - name: Day 11 - part two
    directory: day_11_2
    has_solution: true
